redpanda:
  data_directory: /var/lib/redpanda/data
  node_id: 0
  seed_servers: []
  rpc_server:
    address: 0.0.0.0
    port: 33145
  advertised_rpc_api:
    address: redpanda
    port: 33145
  kafka_api:
    - address: 0.0.0.0
      port: 9092
  advertised_kafka_api:
    - address: redpanda
      port: 9092
  admin:
    - address: 0.0.0.0
      port: 9644
rpk:
  enable_usage_stats: false
